In [ ]:
!pip3 install torch


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import torch
import numpy as np

In [ ]:
from IPython.utils.text import string
v = torch.tensor([1,2,3])
print(v)
print(v.dtype) #getting the data type of the elements of the tensor
print(v[0])
print(v[1])
print(v[2])

tensor([1, 2, 3])
torch.int64
tensor(1)
tensor(2)
tensor(3)


In [ ]:
v1 = torch.tensor([1,2,3,4,5,6])
print(v1)
print(v1.dtype)
print(v1[1:4]) #for getting values using the range of index
print(v1[1:]) #getting values start from particular index to end of the tensor
print(v1[0:]) #getting all elements of the tensor

tensor([1, 2, 3, 4, 5, 6])
torch.int64
tensor([2, 3, 4])
tensor([2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6])


In [ ]:
v2 = torch.FloatTensor([1,2,3,4,5,6]) #creating float tensor
print(v2)
print(v2.dtype)
print(v2.size()) #getting the size of the tensor


tensor([1., 2., 3., 4., 5., 6.])
torch.float32
torch.Size([6])


In [ ]:
print(v1) #show the tensor in 1 row and 6 columns
print(v1.view(6,1)) #Re-shape i.e., getting 6 elements of the tensor in columner order where will shown 6 rows in one column
print(v1.view(3,2)) #reshape- 3 rows and 2 columns
v1.view(3,-1) #although given an invalid row# still show 2 rows as it first got valid column#

tensor([1, 2, 3, 4, 5, 6])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a) #convert numpy array to tensor
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [ ]:
numpy_cnv = tensor_cnv.numpy() #convert tensor to numpy array
print(numpy_cnv)

[1 2 3 4 5]
